server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
            - id: inventory-service-route
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/**
            - id: recommendation-service-route
              uri: lb://RECOMMENDATION-SERVICE
              predicates:
                - Path=/recommendations/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: recommendationCircuitBreaker
                    fallbackUri: forward:/fallback/recommendations

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      recommendationCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      recommendationCircuitBreaker:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
  endpoint:
    health:
      show-details: always